using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WTFGames.Hephaestus.VFX.Editor
{
    /// <summary>
    /// Builds the source code of the VFX keys enum.
    /// </summary>
    internal static class VFXEnumGenerator
    {
        /// <summary>
        /// Joins the parts into a namespace, dropping characters that are not allowed and parts that end up empty.
        /// </summary>
        public static string GetNamespace(params string[] parts)
        {
            var namespaceParts = parts
                .Select(VFXIdentifierUtility.ToNamespacePart)
                .Where(part => part.Length > 0);

            return string.Join(".", namespaceParts);
        }

        public static string Generate(string namespaceName, string enumName, IList<VFXConstantKey> keys)
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.Append("// <auto-generated>\n");
            stringBuilder.Append($"// Generated by the {nameof(VFXLibraryConstants)} inspector. Manual changes will be lost on the next export.\n");
            stringBuilder.Append("// </auto-generated>\n");
            stringBuilder.Append($"namespace {namespaceName}\n");
            stringBuilder.Append("{\n");
            stringBuilder.Append($"\tpublic enum {enumName} : byte\n");
            stringBuilder.Append("\t{\n");

            for (var i = 0; i < keys.Count; i++)
            {
                var comma = i < keys.Count - 1 ? "," : string.Empty;
                stringBuilder.Append($"\t\t{keys[i].name} = {keys[i].id}{comma}\n");
            }

            stringBuilder.Append("\t}\n");
            stringBuilder.Append("}\n");

            return stringBuilder.ToString();
        }
    }
}
