using NUnit.Framework;

namespace WTFGames.Hephaestus.VFX.Editor.Tests
{
    public class VFXEnumGeneratorTests
    {
        [Test]
        public void GetNamespace_JoinsSanitizedParts()
        {
            Assert.AreEqual("WTFGames._3DArena.VFX", VFXEnumGenerator.GetNamespace("WTF Games", "3D Arena", "VFX"));
        }

        [Test]
        public void GetNamespace_DropsEmptyParts()
        {
            Assert.AreEqual("Game.VFX", VFXEnumGenerator.GetNamespace("!!!", "Game", "VFX"));
        }

        [Test]
        public void Generate_WritesKeysWithTheirIds()
        {
            var keys = new[]
            {
                new VFXConstantKey { name = "EXPLOSION", id = 0 },
                new VFXConstantKey { name = "SMOKE", id = 2 }
            };

            var expected =
                "// <auto-generated>\n" +
                "// Generated by the VFXLibraryConstants inspector. Manual changes will be lost on the next export.\n" +
                "// </auto-generated>\n" +
                "namespace Company.Game.VFX\n" +
                "{\n" +
                "\tpublic enum VFXKeys : byte\n" +
                "\t{\n" +
                "\t\tEXPLOSION = 0,\n" +
                "\t\tSMOKE = 2\n" +
                "\t}\n" +
                "}\n";

            Assert.AreEqual(expected, VFXEnumGenerator.Generate("Company.Game.VFX", "VFXKeys", keys));
        }

        [Test]
        public void Generate_NoKeys_WritesEmptyEnum()
        {
            StringAssert.Contains("\tpublic enum VFXKeys : byte\n\t{\n\t}\n", VFXEnumGenerator.Generate("Game.VFX", "VFXKeys", new VFXConstantKey[0]));
        }
    }
}
